version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: db_blog
      POSTGRES_USER: alaidi
      POSTGRES_PASSWORD: alaidi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:80"

volumes:
  pgdata:
